### ISSUE TITLE
where is the requirements.txt

### ISSUE THREAD

**Issue by sabo-gu** [asifrahaman13/superquery#1]

**Comment by asifrahaman13** [comment]
@sabo-gu 

Hi, thanks for raising the concerns. 

I updated the docs. It uses poetry. So, it will not need a requirements.txt file now.  Please check the CONTRIBUTING.md guideline. If you face any issue please let me know.

BTW: The project is still a newbie and lots of work is to be done, including reformatting the code, better error handling, UI, more powerful tools for the SQL query using LLM etc.  I think it will take some 2-4 weeks more to get into good shape.

**Comment by sabo-gu** [comment]
thank you, this problem is finish.

**Comment by asifrahaman13** [comment]
@sabo-gu 

Added the .env template(.env.example)
